[package]
name = "ffnext"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.76"
bytes = "1.5.0"
simplelog = { version = "0.12.2" }
ffmpeg-next = "7.0.0"
ctrlc = "3.4.7"
clap = { version = "4.5.40", features = ["derive"] }
